### ISSUE TITLE
From string

### ISSUE THREAD

**Issue by LoganDark** [possibly-wrong/precision#1]
Sometimes the numbers I have to store won't fit in an int, for example I wanted to store `0.06161151953125` so I had to do some weird tricks:

```
(math::Rational(22532213, 256000000) * 7) / 10
```

I don't even know if this will turn out to be the number that I want.

Is there any way to convert a string to a rational?

**Comment by LoganDark** [comment]
Nevermind...

https://github.com/possibly-wrong/precision/blob/fd385423ee44a3c82032cf68eb3d0e3018afe9a7/math_Rational.h#L32

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/46633835-bd88ce00-cb03-11e8-8613-28574a09c919.png)
![image](https://user-images.githubusercontent.com/4723091/46633838-c1b4eb80-cb03-11e8-8f90-bdb4b942a2ea.png)
???

**Comment by possibly-wrong** [comment]
Thanks for finding this, most recent commit fixes this. The unsigned and signed integer stream I/O is relatively old and has actually seen some use, but the rational I/O was new and hadn't seen as much testing.

**Comment by LoganDark** [comment]
Ty! I'll test and close if the issue disappears

**Comment by LoganDark** [comment]
Works fine with both `std::string("###")` (where ### is any int) and `std::string("###/###")`
